AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance for Service Catalog"

Parameters:
  OwnerId:
    Type: String
    Description: "AWS account ID of the portfolio owner"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-05e9c8b8d9ad7b4e1"  # Replace with a valid AMI ID
      Tags:
        - Key: "Name"
          Value: "ServiceCatalogEC2"


