AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance for Service Catalog"
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "i9n1bowp0b"  # Replace with a valid AMI ID
      Tags:
        - Key: "Name"
          Value: "ServiceCatalogEC2"
