AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance for Service Catalog"

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: "Instance type for EC2"
  OwnerId:
    Type: String
    Description: "AWS account ID of the portfolio owner"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: "ami-05e9c8b8d9ad7b4e1"  # Replace with a valid AMI ID for us-east-1
      Tags:
        - Key: "Name"
          Value: "ServiceCatalogEC2"

